"""Write human_m3.tex: the model 3 rating round (4-5 Oct), the app's three models rated blind on the same sentences.

    python make_human_m3.py <h3 folder>     (key.json and answers_*.json, private: which system each task shows)

Design (build_m3.py): 18 BayanBench test sentences (core and outside sets), each shown for every system, a Latin square
over four team raters (meaning, Arabic, ease) and one reader with dyslexia (ease only), plus 6 comparisons rated by
everyone (two per pair of systems). Rates are over individual team ratings; "changed" leaves out outputs equal to the
source. Intervals: 95%, bootstrap over whole documents (2,000 resamples), as in the bench."""
import collections, json, random, sys
from pathlib import Path

D = Path(sys.argv[1]).expanduser()
key = json.load(open(D / "key.json", encoding="utf-8"))
ans = json.load(open(sorted(D.glob("answers_*.json"))[-1], encoding="utf-8"))
TEAM, READER = {"1", "2", "3", "7"}, "4"
NAMES = {"model3": "Three", "large": "Two", "fast": "Bart"}

ones = collections.defaultdict(list)          # system -> [(doc, rater, answer, unchanged)]
pairs = collections.defaultdict(collections.Counter)
for slot, v in ans.items():
    for t, a in v.get("r", {}).items():
        k = key[t]
        if t[0] == "o":
            ones[k["system"]].append((k["doc"], slot, a, k["unchanged"]))
        else:
            who = "reader" if slot == READER else "team"
            pairs[(k["contrast"], who)][k["a"] if a["p"] == "a" else k["b"] if a["p"] == "b" else "same"] += 1


def rate(rows, q, val):
    v = [a[q] for _, _, a, _ in rows if q in a]
    return 100 * sum(x == val for x in v) / len(v), len(v)


def ci(rows, q, val, n=2000):
    by = collections.defaultdict(list)
    for d, _, a, _ in rows:
        if q in a:
            by[d].append(a[q] == val)
    groups, rng, out = list(by.values()), random.Random(1), []
    for _ in range(n):
        s = [x for g in rng.choices(groups, k=len(groups)) for x in g]
        out.append(100 * sum(s) / len(s))
    out.sort()
    return out[int(0.025 * n)], out[int(0.975 * n) - 1]


m = {}
for s, p in NAMES.items():
    team = [r for r in ones[s] if r[1] in TEAM]
    changed = [r for r in team if not r[3]]
    reader = [r for r in ones[s] if r[1] == READER]
    m[f"hm{p}N"] = len(team)
    m[f"hm{p}Same"] = f"{rate(team, 'm', 'same')[0]:.0f}"
    m[f"hm{p}Major"] = f"{rate(team, 'm', 'major')[0]:.0f}"
    m[f"hm{p}Ok"] = f"{rate(team, 'a', 'ok')[0]:.0f}"
    m[f"hm{p}Easier"] = f"{rate(team, 'e', 'easier')[0]:.0f}"
    m[f"hm{p}EasierCi"] = "{:.0f}--{:.0f}".format(*ci(team, "e", "easier"))
    m[f"hm{p}Harder"] = f"{rate(team, 'e', 'harder')[0]:.0f}"
    m[f"hm{p}ChN"] = len(changed)
    m[f"hm{p}ChSame"] = f"{rate(changed, 'm', 'same')[0]:.0f}"
    m[f"hm{p}ChEasier"] = f"{rate(changed, 'e', 'easier')[0]:.0f}"
    m[f"hm{p}RN"] = len(reader)
    m[f"hm{p}REasier"] = sum(a.get("e") == "easier" for _, _, a, _ in reader)
    m[f"hm{p}RHarder"] = sum(a.get("e") == "harder" for _, _, a, _ in reader)
for (contrast, who), c in pairs.items():
    a, b = contrast.split("-")
    p = "hmP" + "".join(NAMES[x] for x in sorted((a, b), key=list(NAMES).index)) + ("R" if who == "reader" else "")
    first, second = sorted((a, b), key=list(NAMES).index)
    m[p + "First"], m[p + "Second"], m[p + "Same"] = c[first], c[second], c["same"]
    m[p + "Total"] = sum(c.values())
m["hmRaters"] = len(TEAM)
m["hmReaderDone"] = len(ans.get(READER, {}).get("r", {}))
m["hmReaderTotal"] = sum(READER in map(str, k["slots"]) for k in key.values())
with open(Path(__file__).parent / "human_m3.tex", "w", encoding="utf-8") as f:
    f.write("% generated by make_human_m3.py from the model 3 rating round; do not edit\n")
    for k, v in m.items():
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print(open(Path(__file__).parent / "human_m3.tex").read())
