"""Model 3 against the large model the app ships (model 2 AraT5v2 int8), both through the app's current text step, on
the BayanBench core items: writes model3.tex with the numbers the report cites. The comparisons are the bench's own
paired output (`bayanbench score model3 --baseline app`, threshold 0.5), saved in eval/model3/:
dev (the ship gate) gives the \\mThree* macros, test (the confirmation) the \\mThreeT* macros; model 3 with four
beams (#62) the \\mBeam* (dev) and \\mBeamT* (test) macros.
    python make_model3.py"""
import json
from pathlib import Path

HERE = Path(__file__).parent


def signed(x, fmt):
    return format(x, fmt).replace("-", "\\textminus ")


def macros(split, p):
    core = json.load(open(HERE / f"eval/model3/{split}.model3-vs-app.json", encoding="utf-8"))["sets"]["core"]
    kept, same = core["meaning"]["meaning kept"], core["meaning"]["P(same meaning)"]
    m = {
        f"{p}Scored": same["n"],
        f"{p}Core": same["n"] + same["pending"],
        f"{p}Paired": same["diff_n"],
        f"{p}Kept": f"{kept['rate'][0]:.0f}" if "rate" in kept else f"{kept['mean'][0]:.0f}",
        f"{p}KeptDiff": signed(kept["diff"][0], "+.0f"),
        f"{p}KeptCi": f"{signed(kept['diff'][1], '+.0f')}, {signed(kept['diff'][2], '+.0f')}",
        f"{p}Same": f"{same['mean'][0]:.2f}",
        f"{p}SameDiff": signed(same["diff"][0], "+.2f"),
        f"{p}SameCi": f"{signed(same['diff'][1], '+.2f')}, {signed(same['diff'][2], '+.2f')}",
    }
    for key, name, fmt in [("longest clause: words shorter", "Clause", "+.1f"),
                           ("reading level: levels lower", "Level", "+.2f"), ("hard words: fewer", "Hard", "+.2f")]:
        x = core["simpler"][key]
        m[f"{p}{name}"] = format(x["mean"][0], fmt.lstrip("+"))
        m[f"{p}{name}Diff"] = signed(x["diff"][0], fmt)
        m[f"{p}{name}Ci"] = f"{signed(x['diff'][1], fmt)}, {signed(x['diff'][2], fmt)}"
    easy = core["behaviour"]["C: easy text left unchanged"]
    m[f"{p}Easy"] = f"{easy['rate'][0]:.0f}"
    m[f"{p}EasyDiff"] = signed(easy["diff"][0], "+.0f")
    m[f"{p}Numbers"] = f"{core['checks']['numbers kept']['rate'][0]:.0f}"
    # unsigned sizes, for prose that already says the direction ("falls by", "more words")
    m[f"{p}KeptAbs"] = f"{abs(kept['diff'][0]):.0f}"
    m[f"{p}EasyAbs"] = f"{abs(easy['diff'][0]):.0f}"
    for key, name, fmt in [("longest clause: words shorter", "Clause", ".1f"),
                           ("reading level: levels lower", "Level", ".2f"), ("hard words: fewer", "Hard", ".2f")]:
        m[f"{p}{name}Abs"] = format(abs(core["simpler"][key]["diff"][0]), fmt)
    return m


def beam(split, p):
    """Model 3 with four beams (the app since #62) against the app's large model: the code measures, which are
    complete, and how many core items have a meaning score so far."""
    core = json.load(open(HERE / f"eval/model3/{split}.model3b4-vs-app.json", encoding="utf-8"))["sets"]["core"]
    same = core["meaning"]["P(same meaning)"]
    clause = core["simpler"]["longest clause: words shorter"]
    easy = core["behaviour"]["C: easy text left unchanged"]
    return {
        f"{p}Scored": same["n"], f"{p}Core": same["n"] + same["pending"],
        f"{p}ClauseAbs": f"{abs(clause['diff'][0]):.1f}",
        f"{p}ClauseCi": f"{signed(clause['diff'][1], '+.1f')}, {signed(clause['diff'][2], '+.1f')}",
        f"{p}EasyAbs": f"{abs(easy['diff'][0]):.0f}",
        f"{p}Numbers": f"{core['checks']['numbers kept']['rate'][0]:.0f}",
    }


out = {**macros("dev", "mThree"), **macros("test", "mThreeT"), **beam("dev", "mBeam"), **beam("test", "mBeamT")}
with open(HERE / "model3.tex", "w", encoding="utf-8") as f:
    f.write("% generated by make_model3.py from eval/model3/*.model3-vs-app.json; do not edit\n")
    for k, v in out.items():
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print(open(HERE / "model3.tex").read())
